### ISSUE TITLE
Error since v1.0.30 `Failed to resolve entry for package "@studio-freight/lenis"`

### ISSUE THREAD

**Issue by flayks** [darkroomengineering/lenis#275]
**Describe the bug**
Since the latest version, I get an error when running my site locally using Bun (`bun dev`) in a monorepo

```
website:dev:   ✘ [ERROR] Failed to resolve entry for package "@studio-freight/lenis". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
website:dev: 
website:dev:     script:/Users/flayks/sites/portfolio/apps/website/src/components/SmoothScroll.svelte?id=0:3:22:
website:dev:       3 │     import Lenis from '@studio-freight/lenis'
website:dev:         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~
website:dev: 
website:dev:   This error came from the "onResolve" callback registered here:
website:dev: 
website:dev:     ../../node_modules/esbuild/lib/main.js:1292:20:
website:dev:       1292 │       let promise = setup({
website:dev:            ╵                     ^
website:dev: 
website:dev:     at setup (file:///Users/flayks/sites/portfolio/node_modules/astro/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:64112:19)
website:dev:     at handlePlugins (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1292:21)
website:dev:     at buildOrContextImpl (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:978:5)
website:dev:     at Object.buildOrContext (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:787:5)
website:dev:     at /Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:2207:68
website:dev:     at new Promise (<anonymous>)
website:dev:     at Object.context (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:2207:27)
website:dev:     at Object.context (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:2047:58)
website:dev:     at prepareEsbuildScanner (file:///Users/flayks/sites/portfolio/node_modules/astro/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63889:26)
website:dev:     at failureErrorWithLog (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1650:15)
website:dev:     at /Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1058:25
website:dev:     at runOnEndCallbacks (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1485:45)
website:dev:     at buildResponseToResult (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1056:7)
website:dev:     at /Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1068:9
website:dev:     at new Promise (<anonymous>)
website:dev:     at requestCallbacks.on-end (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:1067:54)
website:dev:     at handleRequest (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:731:17)
website:dev:     at handleIncomingPacket (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:756:7)
website:dev:     at Socket.readFromStdout (/Users/flayks/sites/portfolio/node_modules/esbuild/lib/main.js:679:7)
```

No error when sticking to `v1.0.29`, still using the same environment.

Not sure what it's caused by but probably some changes to the main `package.json`?

**Comment by clementroche** [comment]
we just switched from `microbundle` to `rollup`, imma investigate

**Comment by clementroche** [comment]
can you try with "@studio-freight/lenis-test" ?

**Comment by flayks** [comment]
Looks good to me using `"@studio-freight/lenis-test": "latest"`!

**Comment by clementroche** [comment]
so weird, they're both the same

**Comment by clementroche** [comment]
@flayks should be fixed in @1.0.32

**Comment by flayks** [comment]
I get another error now:

```
website:dev: (node:12262) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
website:dev: (Use `node --trace-warnings ...` to show where the warning was created)
website:dev: 13:34:10 [ERROR] Unexpected token 'export'
website:dev:   Stack trace:
website:dev:     at internalCompileFunction (node:internal/vm:77:18)
website:dev:     at Module._compile (node:internal/modules/cjs/loader:1339:27)
website:dev:     at Module.load (node:internal/modules/cjs/loader:1206:32)
website:dev:     at cjsLoader (node:internal/modules/esm/translators:358:17)
website:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
```

**Comment by clementroche** [comment]
are you using next.js @flayks ?

**Comment by flayks** [comment]
No it's happening using Astro here, within a Svelte component.

**Comment by clementroche** [comment]
well, i'm gonna use .mjs instead of .esm.js but it's so weird that lenis-test works

**Comment by clementroche** [comment]
but it's so weird that lenis-test works

**Comment by flayks** [comment]
Alright I might have been a bit fast here since I just ran the `bun dev` command and didn't had any error. I get the same problem when going on the dev url. My bad!

```
/Users/flayks/sites/portfolio/node_modules/@studio-freight/lenis-test/dist/lenis.esm.js:1
function t(t,e,i){return Math.max(t,Math.min(e,i))}class e{advance(e){if(!this.isRunning)return;let i=!1;if(this.lerp)this.value=(s=this.value,o=this.to,n=60*this.lerp,r=e,function(t,e,i){return(1-i)*t+i*e}(s,o,1-Math.exp(-n*r))),Math.round(this.value)===this.to&&(this.value=this.to,i=!0);else{this.currentTime+=e;const s=t(0,this.currentTime/this.duration,1);i=s>=1;const o=i?1:this.easing(s);this.value=this.from+(this.to-this.from)*o}var s,o,n,r;this.onUpdate?.(this.value,i),i&&this.stop()}stop(){this.isRunning=!1}fromTo(t,e,{lerp:i=.1,duration:s=1,easing:o=(t=>t),onStart:n,onUpdate:r}){this.from=this.value=t,this.to=e,this.lerp=i,this.duration=s,this.easing=o,this.currentTime=0,this.isRunning=!0,n?.(),this.onUpdate=r}}class i{constructor({wrapper:t,content:e,autoResize:i=!0}={}){if(this.wrapper=t,this.content=e,i){const t=function(t,e){let i;return function(){let s=arguments,o=this;clearTimeout(i),i=setTimeout((function(){t.apply(o,s)}),e)}}(this.resize,250);this.wrapper!==window&&(this.wrapperResizeObserver=new ResizeObserver(t),this.wrapperResizeObserver.observe(this.wrapper)),this.contentResizeObserver=new ResizeObserver(t),this.contentResizeObserver.observe(this.content)}this.resize()}destroy(){this.wrapperResizeObserver?.disconnect(),this.contentResizeObserver?.disconnect()}resize=()=>{this.onWrapperResize(),this.onContentResize()};onWrapperResize=()=>{this.wrapper===window?(this.width=window.innerWidth,this.height=window.innerHeight):(this.width=this.wrapper.clientWidth,this.height=this.wrapper.clientHeight)};onContentResize=()=>{this.scrollHeight=this.content.scrollHeight,this.scrollWidth=this.content.scrollWidth};get limit(){return{x:this.scrollWidth-this.width,y:this.scrollHeight-this.height}}}class s{constructor(){this.events={}}emit(t,...e){let i=this.events[t]||[];for(let t=0,s=i.length;t<s;t++)i[t](...e)}on(t,e){return this.events[t]?.push(e)||(this.events[t]=[e]),()=>{this.events[t]=this.events[t]?.filter((t=>e!==t))}}off(t,e){this.events[t]=this.events[t]?.filter((t=>e!==t))}destroy(){this.events={}}}class o{constructor(t,{wheelMultiplier:e=1,touchMultiplier:i=2,normalizeWheel:o=!1}){this.element=t,this.wheelMultiplier=e,this.touchMultiplier=i,this.normalizeWheel=o,this.touchStart={x:null,y:null},this.emitter=new s,this.element.addEventListener("wheel",this.onWheel,{passive:!1}),this.element.addEventListener("touchstart",this.onTouchStart,{passive:!1}),this.element.addEventListener("touchmove",this.onTouchMove,{passive:!1}),this.element.addEventListener("touchend",this.onTouchEnd,{passive:!1})}on(t,e){return this.emitter.on(t,e)}destroy(){this.emitter.destroy(),this.element.removeEventListener("wheel",this.onWheel,{passive:!1}),this.element.removeEventListener("touchstart",this.onTouchStart,{passive:!1}),this.element.removeEventListener("touchmove",this.onTouchMove,{passive:!1}),this.element.removeEventListener("touchend",this.onTouchEnd,{passive:!1})}onTouchStart=t=>{const{clientX:e,clientY:i}=t.targetTouches?t.targetTouches[0]:t;this.touchStart.x=e,this.touchStart.y=i,this.lastDelta={x:0,y:0}};onTouchMove=t=>{const{clientX:e,clientY:i}=t.targetTouches?t.targetTouches[0]:t,s=-(e-this.touchStart.x)*this.touchMultiplier,o=-(i-this.touchStart.y)*this.touchMultiplier;this.touchStart.x=e,this.touchStart.y=i,this.lastDelta={x:s,y:o},this.emitter.emit("scroll",{deltaX:s,deltaY:o,event:t})};onTouchEnd=t=>{this.emitter.emit("scroll",{deltaX:this.lastDelta.x,deltaY:this.lastDelta.y,event:t})};onWheel=e=>{let{deltaX:i,deltaY:s}=e;this.normalizeWheel&&(i=t(-100,i,100),s=t(-100,s,100)),i*=this.wheelMultiplier,s*=this.wheelMultiplier,this.emitter.emit("scroll",{deltaX:i,deltaY:s,event:e})}}class n{constructor({wrapper:t=window,content:n=document.documentElement,wheelEventsTarget:r=t,eventsTarget:h=r,smoothWheel:l=!0,smoothTouch:a=!1,syncTouch:c=!1,syncTouchLerp:p=.1,__iosNoInertiaSyncTouchLerp:u=.4,touchInertiaMultiplier:d=35,duration:m,easing:g=(t=>Math.min(1,1.001-Math.pow(2,-10*t))),lerp:v=!m&&.1,infinite:S=!1,orientation:w="vertical",gestureOrientation:f="vertical",touchMultiplier:y=1,wheelMultiplier:T=1,normalizeWheel:z=!1,autoResize:_=!0}={}){window.lenisVersion="0.0.2",t!==document.documentElement&&t!==document.body||(t=window),this.options={wrapper:t,content:n,wheelEventsTarget:r,eventsTarget:h,smoothWheel:l,smoothTouch:a,syncTouch:c,syncTouchLerp:p,__iosNoInertiaSyncTouchLerp:u,touchInertiaMultiplier:d,duration:m,easing:g,lerp:v,infinite:S,gestureOrientation:f,orientation:w,touchMultiplier:y,wheelMultiplier:T,normalizeWheel:z,autoResize:_},this.animate=new e,this.emitter=new s,this.dimensions=new i({wrapper:t,content:n,autoResize:_}),this.toggleClass("lenis",!0),this.velocity=0,this.isLocked=!1,this.isStopped=!1,this.isSmooth=c||l||a,this.isScrolling=!1,this.targetScroll=this.animatedScroll=this.actualScroll,this.options.wrapper.addEventListener("scroll",this.onNativeScroll,{passive:!1}),this.virtualScroll=new o(h,{touchMultiplier:y,wheelMultiplier:T,normalizeWheel:z}),this.virtualScroll.on("scroll",this.onVirtualScroll)}destroy(){this.emitter.destroy(),this.options.wrapper.removeEventListener("scroll",this.onNativeScroll,{passive:!1}),this.virtualScroll.destroy(),this.dimensions.destroy(),this.toggleClass("lenis",!1),this.toggleClass("lenis-smooth",!1),this.toggleClass("lenis-scrolling",!1),this.toggleClass("lenis-stopped",!1),this.toggleClass("lenis-locked",!1)}on(t,e){return this.emitter.on(t,e)}off(t,e){return this.emitter.off(t,e)}setScroll(t){this.isHorizontal?this.rootElement.scrollLeft=t:this.rootElement.scrollTop=t}onVirtualScroll=({deltaX:t,deltaY:e,event:i})=>{if(i.ctrlKey)return;const s=i.type.includes("touch"),o=i.type.includes("wheel");if("both"===this.options.gestureOrientation&&0===t&&0===e||"vertical"===this.options.gestureOrientation&&0===e||"horizontal"===this.options.gestureOrientation&&0===t||s&&"vertical"===this.options.gestureOrientation&&0===this.scroll&&!this.options.infinite&&e<=0)return;let n=i.composedPath();if(n=n.slice(0,n.indexOf(this.rootElement)),n.find((t=>t.hasAttribute?.("data-lenis-prevent")||s&&t.hasAttribute?.("data-lenis-prevent-touch")||o&&t.hasAttribute?.("data-lenis-prevent-wheel")||t.classList?.contains("lenis"))))return;if(this.isStopped||this.isLocked)return void i.preventDefault();if(this.isSmooth=(this.options.smoothTouch||this.options.syncTouch)&&s||this.options.smoothWheel&&o,!this.isSmooth)return this.isScrolling=!1,void this.animate.stop();i.preventDefault();let r=e;"both"===this.options.gestureOrientation?r=Math.abs(e)>Math.abs(t)?e:t:"horizontal"===this.options.gestureOrientation&&(r=t);const h=s&&this.options.syncTouch,l=s&&"touchend"===i.type&&Math.abs(r)>1;l&&(r=this.velocity*this.options.touchInertiaMultiplier),this.scrollTo(this.targetScroll+r,{programmatic:!1,...h&&{lerp:l?this.syncTouchLerp:this.options.__iosNoInertiaSyncTouchLerp}})};resize(){this.dimensions.resize()}emit(){this.emitter.emit("scroll",this)}onNativeScroll=()=>{if(!this.__preventNextScrollEvent&&!this.isScrolling){const t=this.animatedScroll;this.animatedScroll=this.targetScroll=this.actualScroll,this.velocity=0,this.direction=Math.sign(this.animatedScroll-t),this.emit()}};reset(){this.isLocked=!1,this.isScrolling=!1,this.animatedScroll=this.targetScroll=this.actualScroll,this.velocity=0,this.animate.stop()}start(){this.isStopped=!1,this.reset()}stop(){this.isStopped=!0,this.animate.stop(),this.reset()}raf(t){const e=t-(this.time||t);this.time=t,this.animate.advance(.001*e)}scrollTo(e,{offset:i=0,immediate:s=!1,lock:o=!1,duration:n=this.options.duration,easing:r=this.options.easing,lerp:h=!n&&this.options.lerp,onComplete:l=null,force:a=!1,programmatic:c=!0}={}){if(!this.isStopped&&!this.isLocked||a){if(["top","left","start"].includes(e))e=0;else if(["bottom","right","end"].includes(e))e=this.limit;else{let t;if("string"==typeof e?t=document.querySelector(e):e?.nodeType&&(t=e),t){if(this.options.wrapper!==window){const t=this.options.wrapper.getBoundingClientRect();i-=this.isHorizontal?t.left:t.top}const s=t.getBoundingClientRect();e=(this.isHorizontal?s.left:s.top)+this.animatedScroll}}if("number"==typeof e){if(e+=i,e=Math.round(e),this.options.infinite?c&&(this.targetScroll=this.animatedScroll=this.scroll):e=t(0,e,this.limit),s)return this.animatedScroll=this.targetScroll=e,this.setScroll(this.scroll),this.reset(),void l?.(this);if(!c){if(e===this.targetScroll)return;this.targetScroll=e}this.animate.fromTo(this.animatedScroll,e,{duration:n,easing:r,lerp:h,onStart:()=>{o&&(this.isLocked=!0),this.isScrolling=!0},onUpdate:(t,e)=>{this.isScrolling=!0,this.velocity=t-this.animatedScroll,this.direction=Math.sign(this.velocity),this.animatedScroll=t,this.setScroll(this.scroll),c&&(this.targetScroll=t),e||this.emit(),e&&(this.reset(),this.emit(),l?.(this),this.__preventNextScrollEvent=!0,requestAnimationFrame((()=>{delete this.__preventNextScrollEvent})))}})}}}get rootElement(){return this.options.wrapper===window?document.documentElement:this.options.wrapper}get limit(){return this.dimensions.limit[this.isHorizontal?"x":"y"]}get isHorizontal(){return"horizontal"===this.options.orientation}get actualScroll(){return this.isHorizontal?this.rootElement.scrollLeft:this.rootElement.scrollTop}get scroll(){return this.options.infinite?(t=this.animatedScroll,e=this.limit,(t%e+e)%e):this.animatedScroll;var t,e}get progress(){return 0===this.limit?1:this.scroll/this.limit}get isSmooth(){return this.__isSmooth}set isSmooth(t){this.__isSmooth!==t&&(this.__isSmooth=t,this.toggleClass("lenis-smooth",t))}get isScrolling(){return this.__isScrolling}set isScrolling(t){this.__isScrolling!==t&&(this.__isScrolling=t,this.toggleClass("lenis-scrolling",t))}get isStopped(){return this.__isStopped}set isStopped(t){this.__isStopped!==t&&(this.__isStopped=t,this.toggleClass("lenis-stopped",t))}get isLocked(){return this.__isLocked}set isLocked(t){this.__isLocked!==t&&(this.__isLocked=t,this.toggleClass("lenis-locked",t))}get className(){let t="lenis";return this.isStopped&&(t+=" lenis-stopped"),this.isLocked&&(t+=" lenis-locked"),this.isScrolling&&(t+=" lenis-scrolling"),this.isSmooth&&(t+=" lenis-smooth"),t}toggleClass(t,e){this.rootElement.classList.toggle(t,e),this.emitter.emit("className change",this)}}export{n as default};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

SyntaxError: Unexpected token 'export'
```

**Comment by clementroche** [comment]
alright, what about v1.0.33 @flayks  ?

**Comment by flayks** [comment]
Yes! This time it works properly 💪

**Comment by clementroche** [comment]
Thank you so much for your feedback 🙏

**Comment by flayks** [comment]
All good! Thanks for investigating ✌️
